Add files via upload
akhmyarovaAT/first_project pull request #1
Opened 2021-09-26 18:43 UTC by akhmyarovaAT

первое дз

2021-09-29 17:39 UTC, MathPracticum requested changes
нужно пройти тесты
все ячейуи должны отработать

2021-10-08 16:15 UTC, akhmyarovaAT commented
первое дз исправила

2021-10-16 08:13 UTC, MathPracticum commented
у вас теперь 2 файла на 1-е дз, нужно убрать лишнее

2021-10-17 17:28 UTC, akhmyarovaAT commented
убрала

2021-10-28 07:52 UTC, MathPracticum approved these changes

2021-10-31 09:58 UTC, merged